language: python
os: linux
if: branch = master or tag IS present
python: 3.6

before_script: ./setup.py install
    #pip install rkd  # todo: set fixed version

jobs:
    allow_failures:
        env:
            - CAN_FAIL=true

    include:
        - stage: Test on Python 3.6
          python: 3.6
          script:
              - rkd :build
              - cd src && python -m unittest discover -s ../test

        - stage: Test on Python 3.7
          python: 3.7
          script:
              - rkd :build
              - cd src && python -m unittest discover -s ../test

        - stage: Test on Python 3.8
          python: 3.8
          script:
              - rkd :build
              - cd src && python -m unittest discover -s ../test

        - stage: Release
          python: 3.6
          script:
              - ./setup.py install
              - RKD_COMPAT_SUBPROCESS=true rkd :release

        - stage: Test on Python 3.9 (allowed to fail)
          env: CAN_FAIL=true
          python: 3.9
          script:
              - rkd :build
              - cd src && python -m unittest discover -s ../test

        - stage: Test on Python NIGHTLY (allowed to fail)
          env: CAN_FAIL=true
          python: nightly
          script:
              - rkd :build
              - cd src && python -m unittest discover -s ../test
