language: python
os: linux
dist: bionic
if: branch = master or tag IS present
python: 3.6

# important: with limited depth the tags are not cloned properly - the PBR does not work
git:
   depth: false

before_script:
    - pip install -r ./subpackages/rkd_python/requirements.txt

test_script: &test_script
    - whereis python3
    - python --version
    - python3 --version

    # RKD & RKD Core & Standardlib
    - make package
    - make tests

    # Subpackages: rkd_python
    - cd subpackages/rkd_python && make package tests

# show stdout/stderr immediately in tests (in RKD itself the buffering is turned off)
env:
    - PYTHONUNBUFFERED=true

jobs:
    allow_failures:
        env:
            - CAN_FAIL=true

    include:
        - stage: Test on Python 3.6
          python: 3.6
          script: *test_script


        - stage: Test on Python 3.7
          python: 3.7
          script: *test_script

        - stage: Test on Python 3.8
          python: 3.8
          script: *test_script

        - stage: Release
          python: 3.6
          script:
              - make release
              - cd subpackages/rkd_python && make release

        - stage: Test on Python 3.9 (allowed to fail)
          env: CAN_FAIL=true
          python: 3.9
          script: *test_script

        - stage: Test on Python NIGHTLY (allowed to fail)
          env: CAN_FAIL=true
          python: nightly
          script: *test_script
